// use validations/mint/validation.{can_mint_nfts}
// use tests/mocks/fake_tx.{make_settings_reference_input}
// use aiken/merkle_patricia_forestry as mpt
// use tests/mpt/hal_mpt/{initial_trie, trie_with_hal_2, proof_hal_2}

// test can_mint_nfts_0() {
//     let settings_reference_input = make_settings_reference_input()

//     let minting_data_input = make_minting_data_input(mpt.root(initial_trie()), )
//     let minting_data_output = make_minting_data_output()

//     can_mint_nfts(transaction)
// }
